### ISSUE TITLE
The "Firefox Monitor" and "Privacy Policy" strings are not hyperlinked

### ISSUE THREAD

**Issue by Softvision-CristinaBadescu** [mozilla/blurts-addon#30]
[Notes]:
- Based on the [provided visuals](https://mozilla.invisionapp.com/share/KEIV66OTS23#/screens/297625870), the strings are hyperlinked.

[Affected versions]:
- Firefox 60.0.2
- Firefox Monitor 0.01, Branch 2, Branch 3, Branch 5

[Affected Platforms]:
- All Windows

[Prerequisites]:
- Have a clean Firefox profile with the latest Firefox Monitor [Branch 2] installed.

[Steps to reproduce]:
1. Open the Firefox browser with the profile from prerequisites.
2. Navigate to a breached website (eg: https://126.com).
3. Observe the "Firefox Monitor" and "Privacy Policy" strings displayed in the doorhanger.

[Expected result]:
- The strings are hyperlinked.

[Actual result]:
- The strings are not hyperlinked.

[Additional notes]:
- Here is a screenshot with this issue:
Branch 2: 
![variation 2 - pop up](https://user-images.githubusercontent.com/31244235/41404562-34a156fe-6fd0-11e8-8df0-82719ecbb35e.png)
Branch 3: 
![variation 3 - pop up](https://user-images.githubusercontent.com/31244235/41404569-39ce6342-6fd0-11e8-90c7-f284748b5525.png)
Branch 5: 
![variation 5 - linked in - pop up](https://user-images.githubusercontent.com/31244235/41404575-3ebccc54-6fd0-11e8-8647-009ad0c27c6e.png)

**Comment by pdehaan** [comment]
I think this is because we're calling `doc.createTextNode()` versus creating a bunch of DOM elements, per: https://github.com/mozilla/blurts-addon/pull/8/files#diff-d5ade8022dfcfe489461af1c31b756d9R221

```js
elt.appendChild(doc.createTextNode(site.Title + " was reported to Firefox Monitor, a service that collects information about data breaches and other ways hackers can steal your information.\n\nEnter your email to find out if your account was included in a data breach. (Note: Your email will not be stored. Find out more in our Privacy Policy.)"));
```

But yes, having to submit an email address, click "Search Firefox Monitor", browse that site for the Privacy link (which directs users to https://www.mozilla.org/privacy/websites/) is a somewhat clumsy flow. I haven't checked the Mozilla Privacy notice to see if it details email storage policies, or if we'd ultimately need specific legal pages for the Firefox Monitor site.

**Comment by Softvision-CristinaBadescu** [comment]
This issue is no longer reproducible with the latest version of the "Firefox Monitor" add-on (0.01 custom built on 27.06.2018) installed, on the latest Firefox release (61.0). Verified on Windows 10 x64.
