### ISSUE TITLE
No error is displayed if the user scans an invalid email address on the Firefox Monitor Landing Page

### ISSUE THREAD

**Issue by Softvision-CristinaBadescu** [mozilla/blurts-addon#35]
[Affected versions]:
- Firefox 60.0.2

[Affected Platforms]:
- All Windows

[Steps to reproduce]:
1. Open the browser with the profile from prerequisites.
2. Navigate to "https://fx-breach-alerts.herokuapp.com/" page.
3. Type an invalid email address (example@test).
3. Click the "Search" button and observe the behavior.

[Expected result]:
- An error message informing the user that he should enter a valid email address is displayed.

[Actual result]:
- Nothing happens.

[Notes]:
- Here is a screen recording with this issue:
![firefox monitor - invalid email](https://user-images.githubusercontent.com/31244235/41422108-e8c3346a-7000-11e8-8eb5-0714f208fdd9.gif)

**Comment by pdehaan** [comment]
I was noticing this too this morning when I accidentally typoed an email address and sat there for like 30 seconds waiting for something to happen.
I think the problem is that the Search button is semi-disabled, but still has hover effects so it APPEARS like a clickable button. Seems like maybe we need a more obvious disabled state without hover maybe (possibly in addition to better messaging).

**Comment by Softvision-CristinaBadescu** [comment]
This issue is no longer reproducible using the latest version of the "Firefox Monitor" add-on (1.0 custom built on 2018-06-29), on the latest Firefox Release 61.0. Verified on Windows 10 x64.
