### ISSUE TITLE
Beta&Dev Edition 61 - The doorhangers are not triggered when navigating to a breached website

### ISSUE THREAD

**Issue by SoftVision-CarmenFat** [mozilla/blurts-addon#48]
[Notes]:
Regression window wanted:
- Last good revision: 7f92f91fa85d78c434709ec162d4320c5ee686fd
- First bad revision: fa02de71ebf73aea9f5d30b591aacd83b3440bd3
- Pushlog:
https://hg.mozilla.org/integration/autoland/pushloghtml?fromchange=7f92f91fa85d78c434709ec162d4320c5ee686fd&tochange=fa02de71ebf73aea9f5d30b591aacd83b3440bd3

Seems that bug [1454820](https://bugzilla.mozilla.org/show_bug.cgi?id=1454820) introduced this regression.

[Affected versions]:
- Firefox Beta 61.0b14
- Firefox Dev Edition 61.0b14
- Firefox Monitor 0.01, all Branches

[Affected Platforms]:
- All Windows

[Prerequisites]:
- "xpinstall.signatures.required" pref is set to false
- Firefox Monitor is installed through "about:debugging" page.

[Steps to reproduce]:
1. Open the Firefox browser with the profile from prerequisites.
2. Navigate to a breached website (eg. https://bitly.com/).
3. Observe what happens next.

[Expected result]:
- The Firefox Monitor doorhanger is displayed.

[Actual result]:
- The Firefox Monitor doorhanger is not displayed.

[Notes]:
- The following error is displayed in the Broswer console when installing the study:
`TypeError: browser.study is undefined`
- Added a screen recording with the issue:

![61 is broken](https://user-images.githubusercontent.com/26000308/41588223-d8b4317a-73b9-11e8-96db-db496987d70f.gif)

**Comment by nhnt11** [comment]
FWIW, the issue with things not working on Beta is because Beta is built with legacy extensions disabled (and not even overridable with a pref).

WebExtension Experiments work if one of the following conditions is met:
 - The Firefox build supports legacy extensions
 - The add-on is privileged

So in order to test the add-on in Beta we either need to build 61 from source with MOZ_ALLOW_LEGACY_EXTENSIONS set in the build environment, or sign the add-on to make it privileged.

Hope this helps.
